Repository netgrif/components, pull requests merged in 2022-09, with the labels that each got.

#56 [NAE-1635] Tree view has incorrect object for set data
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/case-tree.service.spec.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/case-tree.service.ts
Labels: bugfix, Extra Small

#58 [NAE-1430] Generated sidenav ignores inputs
  projects/nae-example-app/src/app/doc/drawer-example/drawer-example.component.html
  projects/netgrif-components/schematics/view/create-view-prompt/views/sidenav-toolbar-view/create-sidenav-or-toolbar-view.ts
Labels: bugfix, Extra Small

#59 [NAE-1427] Allowed nets factory ignores allowedNets in nae.json
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/create-case-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/tabbed/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/task-view/files/simple/__className@dasherize__.component.ts.template
Labels: bugfix, Extra Small

#61 [NAE-1639] Non-Latin1 characters cannot be used in passwords
  projects/nae-example-app/src/polyfills.ts
  projects/netgrif-components-core/src/lib/authentication/services/methods/basic-authentication/basic-authentication.service.spec.ts
  projects/netgrif-components-core/src/lib/authentication/services/methods/basic-authentication/basic-authentication.service.ts
Labels: bugfix, Extra Small

#66 [NAE-1606] Configuration of case creation button from menu item
  projects/nae-example-app/src/app/doc/case-view/case-view.component.html
  projects/nae-example-app/src/app/doc/case-view/case-view.component.ts
  projects/nae-example-app/src/app/doc/demo-title-config/content/1/demo-title-config-content1-case-view.component.html
  projects/nae-example-app/src/app/doc/demo-title-config/content/2/demo-title-config-content2-case-view.component.html
  projects/nae-example-app/src/app/doc/demo-title-config/content/3/demo-title-config-content3-case-view.component.html
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.html
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/model/new-case-injection-data.ts
  projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.ts
  projects/netgrif-components-core/src/lib/view/case-view/tabbed-case-view.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.html
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/model/injected-tabbed-case-view-data-with-navigation-item-task-data.ts
  projects/netgrif-components/src/lib/view/case-view/case-view.module.ts
  projects/netgrif-components/src/lib/view/case-view/components/create-case-button/create-case-button.component.html
  projects/netgrif-components/src/lib/view/case-view/components/create-case-button/create-case-button.component.scss
  projects/netgrif-components/src/lib/view/case-view/components/create-case-button/create-case-button.component.spec.ts
  projects/netgrif-components/src/lib/view/case-view/components/create-case-button/create-case-button.component.ts
  projects/netgrif-components/src/lib/view/public-api.ts
Labels: improvement, Medium

#91 [NAE-1679] User list frontend component
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/abstract-user-assign.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/model/user-list-injected-data.ts
  projects/netgrif-components-core/src/lib/task-content/model/field-type-resource.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-stepper-field/enumeration-stepper-field.component.scss
  projects/netgrif-components/src/lib/data-fields/public-api.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.scss
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts
  projects/netgrif-components/src/lib/task-content/field-component-resolver/field-component-resolver.component.html
Labels: improvement, new feature, Large

#98 [NAE-1626] Trigger of set event for fileList value deletion is not implemented
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-stepper-field/enumeration-stepper-field.component.scss
Labels: bugfix, Extra Small

#100 [NAE-1650] Multichoice autocomplete field component missing
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.html
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.scss
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.ts
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-field.component.html
Labels: new feature, Large

#57 [NAE-1631] Process download in workflow view
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/petri-net-resource.service.spec.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/petri-net-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-petrinet-resource.service.ts
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.html
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.ts
Labels: new feature, Small

#60 [NAE-1437] Missing view components schematics
  docs/nae.schema.json
  projects/nae-example-app/src/app/nae-example-app-view.service.ts
  projects/netgrif-components-core/schematics/_commons/schema.d.ts
  projects/netgrif-components-core/schematics/_commons/view-class-info.ts
  projects/netgrif-components-core/src/commons/schema.ts
  projects/netgrif-components-core/src/schema/nae-schema.json
  projects/netgrif-components/schematics/_commons/view-class-info.ts
  projects/netgrif-components/schematics/view/create-view-prompt/models/create-view-arguments.ts
  projects/netgrif-components/schematics/view/create-view-prompt/schema-create-view-prompt.json
  projects/netgrif-components/schematics/view/create-view-prompt/schematic-create-view-prompt.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/role-assignment-view/files/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/role-assignment-view/files/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/role-assignment-view/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/role-assignment-view/role-assignment-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/workflow-view/create-workflow-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/workflow-view/files/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/workflow-view/files/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/workflow-view/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view/models/nullable-create-view-arguments.ts
  projects/netgrif-components/schematics/view/create-view/schematic-create-view.ts
Labels: improvement, Medium

#94 [NAE-1695] Fix generated tests in schematics
  nae.json
  projects/nae-example-app/src/app/doc/case-view/case-view.component.scss
  projects/nae-example-app/src/app/doc/public-resolver/public-resolver.component.spec.ts
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.spec.ts
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.scss
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.spec.ts
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.scss
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.spec.ts
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.scss
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.scss
  projects/nae-example-app/src/app/doc/task-view/task-view.component.scss
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/create-case-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/common/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/common/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/simple/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/simple/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/tabbed/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/tabbed/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/dashboard-view/create-dashboard-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/dashboard-view/files/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/group-view/files/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/group-view/files/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-resolver-view/files/common/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-single-task-view/files/common/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-single-task-view/files/common/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-task-view/files/common/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-task-view/files/common/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/files/common/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/task-view/files/common/__className@dasherize__.component.spec.ts.template
Labels: improvement, Extra Large

#95 [NAE-1662] Navigation breadcrumbs
  nae.json
  projects/nae-example-app/src/app/app.module.ts
  projects/nae-example-app/src/app/doc/breadcrumbs-example/breadcrumbs-example.component.html
  projects/nae-example-app/src/app/doc/breadcrumbs-example/breadcrumbs-example.component.scss
  projects/nae-example-app/src/app/doc/breadcrumbs-example/breadcrumbs-example.component.spec.ts
  projects/nae-example-app/src/app/doc/breadcrumbs-example/breadcrumbs-example.component.ts
  projects/nae-example-app/src/app/nae-example-app-view.service.ts
  projects/netgrif-components-core/src/lib/navigation/breadcrumbs/abstract-breadcrumbs.component.ts
  projects/netgrif-components-core/src/lib/navigation/public-api.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.ts
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.html
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.scss
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.spec.ts
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.ts
  projects/netgrif-components/src/lib/navigation/navigation.module.ts
  projects/netgrif-components/src/lib/navigation/public-api.ts
Labels: improvement, Medium

#97 [NAE-1436] Create all views schematic
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/schematics/_commons/view-class-info.ts
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/commons/view-class-info.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-petrinet-resource.service.ts
  projects/netgrif-components/schematics/_commons/view-class-info.ts
  projects/netgrif-components/schematics/view/create-view-prompt/models/create-view-arguments.ts
  projects/netgrif-components/schematics/view/create-view-prompt/schema-create-view-prompt.json
  projects/netgrif-components/schematics/view/create-view-prompt/schematic-create-view-prompt.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/ldap-role-assignment-view/files/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/ldap-role-assignment-view/files/__className@dasherize__.component.scss.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/ldap-role-assignment-view/files/__className@dasherize__.component.spec.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/ldap-role-assignment-view/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/ldap-role-assignment-view/ldap-role-assignment-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/login/files/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/login/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/sidenav-toolbar-view/create-sidenav-or-toolbar-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/sidenav-toolbar-view/files/__className@dasherize__.component.html.template
  projects/netgrif-components/schematics/view/create-view-prompt/views/workflow-view/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/schematics/view/create-view/schematic-create-view.ts
  projects/netgrif-components/src/commons/view-class-info.ts
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.scss
Labels: Large

#101 [NAE-1708] Fix lint issues
  CHANGELOG.md
  docs/compodoc/components-core/classes/SnackBar.html
  docs/compodoc/components-core/components/SnackBar.html
  docs/compodoc/components-core/coverage.html
  docs/compodoc/components-core/unit-test.html
  docs/typedoc/components-core/classes/ErrorSnackBarComponent.html
  docs/typedoc/components-core/classes/GenericSnackBarComponent.html
  docs/typedoc/components-core/classes/SnackBar.html
  docs/typedoc/components-core/classes/SuccessSnackBarComponent.html
  docs/typedoc/components-core/classes/WarningSnackBarComponent.html
  projects/netgrif-components-core/src/lib/admin/public-api.ts
  projects/netgrif-components-core/src/lib/admin/role-assignment-ldap-group/abstract-ldap-group-role-assignment.component.ts
  projects/netgrif-components-core/src/lib/dialog/components/alert-dialog/alert-dialog.component.ts
  projects/netgrif-components-core/src/lib/dialog/components/confirm-dialog/confirm-dialog.component.ts
  projects/netgrif-components-core/src/lib/dialog/components/prompt-dialog/prompt-dialog.component.ts
  projects/netgrif-components-core/src/lib/dialog/models/abstract-dialog.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/abstract-task-list.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/default-task-panel-list/abstract-default-task-list.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/task-panel-list-pagination/abstract-task-list-pagination.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/components/error-snack-bar/error-snack-bar.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/components/generic-snack-bar/generic-snack-bar.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/components/success-snack-bar/success-snack-bar.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/components/warning-snack-bar/warning-snack-bar.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/models/abstract-snack-bar.component.ts
  projects/netgrif-components-core/src/lib/snack-bar/public-api.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/default-case-list/abstract-default-case-list.component.ts
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.ts
Labels: improvement, Medium

#83 [NAE-1156] View Deprecation and All Data
  projects/netgrif-components-core/src/lib/data-fields/button-field/abstract-button-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/button-field/models/button-field.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/abstract-enumeration-autocomplete-dynamic-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-icon-field/abstract-enumeration-icon-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/dynamic-enumeration-field.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/abstract-i18n-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/models/multichoice-field.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/text-field/models/text-area-field.ts
  projects/netgrif-components-core/src/lib/data-fields/text-field/models/text-field.ts
  projects/netgrif-components-core/src/lib/resources/interface/fields.ts
  projects/netgrif-components-core/src/lib/task-content/model/resource-interface.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.spec.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/task-view/files/common/__className@dasherize__.component.scss.template
  projects/netgrif-components/src/lib/data-fields/button-field/button-field.component.html
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-stepper-field/enumeration-stepper-field.component.scss
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-field.component.html
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-field.component.html
  projects/netgrif-components/src/lib/data-fields/number-field/number-field.component.html
  projects/netgrif-components/src/lib/data-fields/number-field/number-field.component.ts
  projects/netgrif-components/src/lib/data-fields/text-field/text-field.component.html
Labels: breaking change, Large

#105 [NAE-1719] Auto finish no data does not work without auto assign
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components-core/src/lib/task/services/finish-policy.service.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.ts
Labels: bugfix, Extra Small

#107 Release 6.2.1
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components-core/src/lib/task/services/finish-policy.service.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.ts
Labels: Extra Small

#111 [NAE-1713] Advanced search searching based on case data does not work
  projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
Labels: bugfix, Extra Small

#110 [NAE-1712] Advanced search in case of date operators is blinking (very quickly opening and closing)
  projects/netgrif-components-core/src/lib/search/search-operand-input-component/abstract-search-operand-input.component.ts
  projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html
Labels: Extra Small

#108 [NAE-1721] Create case event bad handling on frontend
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
Labels: bugfix, Extra Small

#102 [NAE-1693] TaskController deleteFile endpoint lacks data about tasks
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
Labels: improvement, bugfix, Extra Small

#109 [NAE-1717] Banned roles not hiding menu entries
  projects/netgrif-components-core/src/commons/schema.ts
  projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-uri-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts
Labels: bugfix, Large

#117 Release 6.2.2
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/commons/schema.ts
  projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
  projects/netgrif-components-core/src/lib/search/search-operand-input-component/abstract-search-operand-input.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
  projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-uri-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html
Labels: Extra Large, release

#118 Release 6.2.2
  .github/config.yml
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/commons/schema.ts
  projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
  projects/netgrif-components-core/src/lib/search/search-operand-input-component/abstract-search-operand-input.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
  projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-uri-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html
Labels: Extra Large, release
