Repository netgrif/components, pull requests merged in 2022-10, with the labels that each got.

#122 [NAE-1731] Missing write access to /home/.../node_modules/@netgrif/components
  package.json
Labels: Extra Small

#123 [NAE-1732] LDAP group role assignment component tile tooltip
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html
Labels: Extra Small

#124 [NAE-1734] Overlay on login page
  projects/netgrif-components-core/src/lib/authentication/components/abstract-authentication-overlay.ts
Labels: bugfix, Extra Small

#121 [NAE-1729] User field null value on frontend throwing error
  projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html
Labels: bugfix, Extra Small

#128 [NAE-1738] Multichoice map autocomplete init key
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.html
Labels: bugfix, Extra Small

#127 [NAE-1737] Bug i18n field placeholder
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.html
Labels: Extra Small

#126 [NAE-1736] Rich textarea fix cursor
  projects/netgrif-components/src/lib/data-fields/text-field/rich-textarea-field/easymde-wrapper/easymde-wrapper.component.ts
Labels: Extra Small

#132 [NAE-1367] Boolean does not have desc
  projects/netgrif-components/src/lib/data-fields/boolean-field/boolean-field.component.html
  projects/netgrif-components/src/lib/data-fields/boolean-field/boolean-field.component.scss
Labels: improvement, bugfix, Extra Small

#131 [NAE-1741] 'Undefined' error on frontend when checking i18n translation equality
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field.ts
Labels: bugfix, Extra Small

#129 [NAE-1739] Currency symbol is displayed on new line, when editing currency field
  projects/netgrif-components/nae-theme.scss
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.html
  projects/netgrif-components/src/lib/data-fields/file-field/file-field.component.scss
  projects/netgrif-components/src/lib/data-fields/number-field/number-currency-field/number-currency-field.component.html
  projects/netgrif-components/src/lib/data-fields/number-field/number-currency-field/number-currency-field.component.scss
Labels: bugfix, Extra Small

#135 [NAE-1743] File preview change to null object
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
Labels: Extra Small

#139 [NAE-1744] Public view does not work delete file
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts
Labels: Extra Small

#138 [NAE-1745] Enumeration autocomplete constantly sending value
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
Labels: bugfix, Extra Small

#140 [NAE-1751] Autocomplete new filter "include"
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-filter-property.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-filter-property.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
Labels: Small

#142 Release/6.2.4
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-filter-property.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-filter-property.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
Labels: release, Medium

#146 [NAE-1762] Public view URL encoding
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
  projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-petri-net-resource.service.ts
Labels: improvement, Extra Small

#144 [NAE-1754] Currency field not displaying symbol
  projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
Labels: bugfix, Extra Small
