Repository netgrif/components, pull requests merged in 2022-02, with the labels that each got.

#3 [NAE-1574] Net role permission checking
  projects/netgrif-components-core/src/lib/authorization/permission/permission.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/permission/permission.service.ts
Labels: breaking change, bugfix, critical, Extra Small

#12 [NAE-1580] Grammar check
  projects/netgrif-components-core/src/assets/i18n/sk.json
Labels: bugfix, Extra Small

#5 [NAE-1557] Cannot clear optional enumeration
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-list-field/abstract-enumeration-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/enumeration-autocomplete-dynamic-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-list-field/enumeration-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-select-field/enumeration-select-field.component.html
Labels: bugfix, Extra Small

#11 [NAE-1575] User select component trying open non-exisisting side menu component
  projects/netgrif-components-core/src/lib/side-menu/services/side-menu.service.ts
Labels: bugfix, Extra Small

#10 [NAE-1577] Task reffed change behavior does not propagate
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
Labels: bugfix, Extra Small

#8 [NAE-1524] Header search by author is not working
  projects/netgrif-components-core/src/lib/header/case-header/case-header.service.ts
  projects/netgrif-components-core/src/lib/search/models/category/no-configuration-user-autocomplete-category.ts
Labels: bugfix, Extra Small

#7 [NAE-1472] MaterialAppearance property on AbstractDataField
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
Labels: bugfix, Extra Small

#6 [NAE-1459] Loading indicator on login and registration related components
  projects/nae-example-app/src/app/doc/forms/email-form/password-form.component.ts
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.spec.ts
  projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.ts
  projects/netgrif-components-core/src/lib/forms/models/abstract-registration.component.ts
  projects/netgrif-components/src/lib/forms/email-submission/email-submission-form.component.html
  projects/netgrif-components/src/lib/forms/forgotten-password/forgotten-password-form.component.html
  projects/netgrif-components/src/lib/forms/registration/registration-form.component.html
Labels: bugfix, Small

#4 [NAE-1455] Navigation menu closes on small screens and cannot be reopened
  projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.ts
  projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.html
  projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.scss
Labels: bugfix, Small

#13 [NAE-1583] Broken FileField/FileListField placeholder
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
Labels: bugfix, Extra Small
