Repository netgrif/components, pull requests merged in 2022-08, with the labels that each got.

#87 [NAE-1682] Translate tooltip admin view
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html
  projects/netgrif-components/src/lib/admin/role-assignment/role-assignment.component.html
  projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.html
  projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.ts
Labels: improvement, Extra Small

#86 [NAE-1680] Public view + change behavior bug
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts
Labels: bugfix, Extra Small

#88 [NAE-1681] Delete file function works with parent task in taskRef-ed file field.
  projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
Labels: bugfix, Extra Small

#89 [NAE-1690] Fix header responsive overflow mode
  projects/netgrif-components-core/src/lib/header/abstract-header-service.ts
  projects/netgrif-components-core/src/lib/header/abstract-header.component.spec.ts
  projects/netgrif-components-core/src/lib/header/abstract-header.component.ts
  projects/netgrif-components-core/src/lib/header/case-header/case-header.service.ts
  projects/netgrif-components-core/src/lib/header/task-header/task-header.service.ts
  projects/netgrif-components-core/src/lib/header/workflow-header/workflow-header.service.ts
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
  projects/netgrif-components-core/src/lib/panel/case-panel/abstract-case-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.ts
  projects/netgrif-components/src/lib/header/header-modes/edit-mode/edit-mode.component.html
  projects/netgrif-components/src/lib/header/header-modes/edit-mode/edit-mode.component.spec.ts
  projects/netgrif-components/src/lib/header/header-modes/loading-mode/loading-mode.component.html
  projects/netgrif-components/src/lib/header/header-modes/loading-mode/loading-mode.component.spec.ts
  projects/netgrif-components/src/lib/header/header-modes/search-mode/search-mode.component.html
  projects/netgrif-components/src/lib/header/header-modes/search-mode/search-mode.component.spec.ts
  projects/netgrif-components/src/lib/header/header-modes/sort-mode/sort-mode.component.html
  projects/netgrif-components/src/lib/header/header-modes/sort-mode/sort-mode.component.spec.ts
  projects/netgrif-components/src/lib/header/header.component.spec.ts
  projects/netgrif-components/src/lib/header/header.component.ts
  projects/netgrif-components/src/lib/header/header.theme.scss
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-simple-task-view/default-simple-task-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-task-view/default-tabbed-task-view.component.spec.ts
  projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.html
  projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.html
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.ts
  projects/netgrif-components/src/lib/view/workflow-view/workflow-view.component.spec.ts
Labels: breaking change, bugfix, Extra Large

#85 [NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: bugfix, Small

#84 [NAE-1643] Configure public view via request parameters
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.html
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.ts
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
  projects/netgrif-components-core/src/lib/panel/abstract-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/abstract-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/configuration/config-params.ts
  projects/netgrif-components-core/src/lib/panel/public-api.ts
  projects/netgrif-components-core/src/lib/public/factories/public-factory-resolver.ts
  projects/netgrif-components-core/src/lib/routing/redirect-service/redirect.service.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/save-filter/abstract-save-filter.component.ts
  projects/netgrif-components-core/src/lib/view/abstract/view-with-headers.ts
  projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.ts
  projects/netgrif-components-core/src/lib/view/case-view/tabbed-case-view.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-task-view.ts
  projects/netgrif-components-core/src/lib/view/task-view/tabbed-task-view.ts
  projects/netgrif-components-core/src/lib/view/workflow-view/abstract-workflow-view.component.ts
  projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/panel.component.html
  projects/netgrif-components/src/lib/panel/panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/panel.component.ts
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.spec.ts
Labels: improvement, Large

#90 [NAE-1690] Fix header responsive overflow mode
  projects/nae-example-app/src/app/doc/case-view/case-view.component.ts
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.ts
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.ts
  projects/nae-example-app/src/app/doc/task-view/task-view.component.ts
  projects/netgrif-components-core/src/lib/header/abstract-header-service.ts
  projects/netgrif-components-core/src/lib/header/abstract-header.component.ts
  projects/netgrif-components-core/src/lib/header/services/overflow.service.ts
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-header-binding.ts
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
  projects/netgrif-components-core/src/lib/panel/case-panel/abstract-case-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/case-panel/abstract-case-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.ts
  projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.ts
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.ts
Labels: Medium

#93 [NAE-1701] Reload validity on the change required field
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
Labels: bug, bugfix, Extra Small

#96 [NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
Labels: Small

#99 [NAE-1701] Reload validity on the change required field
  .github/PULL_REQUEST_TEMPLATE.md
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
Labels: bugfix, Extra Small
