Repository netgrif/components, pull requests merged in 2022-12, with the labels that each got.

#150 Release/6.2.5
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/nae-theme.scss
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.html
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
Labels: release, Medium

#155 Release/6.2.5
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/nae-theme.scss
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.html
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
Labels: release, Medium

#157 [NAE-1799] Multilevel process identifier handling in 6.2.x for public view
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
  projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-petri-net-resource.service.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/files/common/__className@dasherize__.component.ts.template
Labels: bugfix, Extra Small

#160 Release/6.2.6
  CHANGELOG.md
  package.json
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-petri-net-resource.service.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/files/common/__className@dasherize__.component.ts.template
  projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html
Labels: Extra Small, release

#152 [NAE-1674] Uri node cases pagination
  projects/netgrif-components-core/src/lib/navigation/model/size-menu-injection-token.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/public-api.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.ts
  projects/netgrif-components-core/src/lib/utility/is-empty.pipe.spec.ts
  projects/netgrif-components-core/src/lib/utility/is-empty.pipe.ts
  projects/netgrif-components-core/src/lib/utility/is-non-empty.pipe.spec.ts
  projects/netgrif-components-core/src/lib/utility/is-non-empty.pipe.ts
  projects/netgrif-components-core/src/lib/utility/public-api.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-case-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-uri-resource.service.ts
  projects/netgrif-components-core/src/lib/utility/utility.module.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
  projects/netgrif-components/src/lib/navigation/navigation.module.ts
Labels: improvement, Extra Large

#161 [NAE-1803] UserListComponent validations bug
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
Labels: bugfix, Extra Small

#162 Release/6.2.7
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
Labels: Extra Small, release

#163 Release/6.2.7
  CHANGELOG.md
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
Labels: Extra Small, release

#153 [NAE-1795] Breadcrumbs based on the menu, not on the currently displayed view
  projects/netgrif-components-core/src/lib/navigation/breadcrumbs/abstract-breadcrumbs.component.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
Labels: bugfix, critical, Medium

#156 [NAE-1797] I18N field at asynchronous rendering
  projects/netgrif-components-core/src/lib/task-content/task-content/abstract-task-content.component.ts
Labels: Extra Small

#154 [NAE-1790] Validation message on the date field is not displaying correctly
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/abstract-time-instance-field.component.ts
Labels: bugfix, Extra Small

#151 [NAE-1759] Update documentation of public views, PDF generator and user list
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-resolver-view/create-public-resolver-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-single-task-view/create-public-single-task-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-task-view/create-public-task-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/create-public-workflow-view.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/files/common/__className@dasherize__.component.ts.template
Labels: Extra Small
