Repository netgrif/components, pull requests merged in 2022-03, with the labels that each got.

#14 [NAE-1577] Task reffed change behavior does not propagate - correction
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/resources/interface/data-groups.ts
  projects/netgrif-components-core/src/lib/task-content/model/task-fields.ts
  projects/netgrif-components-core/src/lib/task-content/public-api.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.spec.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: Small

#15 [NAE-1586] Virtual scroll is broken everywhere on page
  projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.scss
Labels: bugfix, Extra Small

#16 [NAE-1389] Immediate map data fields display their keys
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
  projects/netgrif-components-core/src/lib/resources/interface/immediate-data.ts
Labels: bugfix, Extra Small

#19 Release 6.0.2
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  .github/workflows/master-build.yml
  CHANGELOG.md
  README.md
  package.json
  projects/nae-example-app/src/app/doc/forms/email-form/password-form.component.ts
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/authorization/permission/permission.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/permission/permission.service.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-list-field/abstract-enumeration-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.spec.ts
  projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.ts
  projects/netgrif-components-core/src/lib/forms/models/abstract-registration.component.ts
  projects/netgrif-components-core/src/lib/header/case-header/case-header.service.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.ts
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
  projects/netgrif-components-core/src/lib/resources/interface/data-groups.ts
  projects/netgrif-components-core/src/lib/resources/interface/immediate-data.ts
  projects/netgrif-components-core/src/lib/search/models/category/no-configuration-user-autocomplete-category.ts
  projects/netgrif-components-core/src/lib/side-menu/services/side-menu.service.ts
  projects/netgrif-components-core/src/lib/task-content/model/task-fields.ts
  projects/netgrif-components-core/src/lib/task-content/public-api.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.spec.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
  projects/netgrif-components-core/src/lib/task/services/assign-policy.service.ts
  projects/netgrif-components-core/src/lib/task/services/finish-policy.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/enumeration-autocomplete-dynamic-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-list-field/enumeration-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-select-field/enumeration-select-field.component.html
  projects/netgrif-components/src/lib/forms/email-submission/email-submission-form.component.html
  projects/netgrif-components/src/lib/forms/forgotten-password/forgotten-password-form.component.html
  projects/netgrif-components/src/lib/forms/registration/registration-form.component.html
  projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.html
  projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.scss
Labels: documentation, improvement, bugfix, release, Large

#23 [NAE-1608] Configuration service getViewByUrl not working with /**
  projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
Labels: bugfix, Extra Small

#20 [NAE-1592] UserService user$ observable null value not checked
  projects/nae-example-app/src/app/doc/public-resolver/public-resolver.component.ts
  projects/netgrif-components-core/src/lib/authentication/components/abstract-authentication-overlay.ts
  projects/netgrif-components-core/src/lib/groups/services/next-group.service.ts
Labels: bugfix, critical, Extra Small

#21 [NAE-1590] Taskref with file field must be assigned
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/file-field-id-body.ts
Labels: bugfix, Extra Small

#18 [NAE-1571] Change the Version.NEWEST from "^" to "latest"
  .gitignore
  projects/netgrif-components-core/src/lib/process/process.service.ts
Labels: breaking change, bugfix, Extra Small

#27 [NAE-1613] Text selection in field value prevents task expansion panel header from reacting to click events
  projects/netgrif-components/src/lib/panel/panel.component.scss
Labels: bugfix, Extra Small

#33 6.0.3
  .github/config.yml
  .gitignore
  CHANGELOG.md
  package.json
  projects/nae-example-app/src/app/doc/public-resolver/public-resolver.component.ts
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/authentication/components/abstract-authentication-overlay.ts
  projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/file-field-id-body.ts
  projects/netgrif-components-core/src/lib/groups/services/next-group.service.ts
  projects/netgrif-components-core/src/lib/process/process.service.ts
  projects/netgrif-components/package.json
Labels: Small
