Repository netgrif/components, pull requests merged in 2022-04, with the labels that each got.

#35 [NAE-1601] Component preview field is not propagated into taskRef
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
Labels: Extra Small

#36 [NAE-1597] New case process input is not validated
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
  projects/netgrif-components/src/lib/side-menu/content-components/new-case/new-case.component.html
Labels: Extra Small

#29 [NAE-1615] Finish button randomly throws error and does not sends request
  projects/netgrif-components-core/src/lib/task/services/finish-task.service.ts
Labels: bugfix, Extra Small

#31 [NAE-1619] Task that has no fields cannot be completed
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: bugfix, Extra Small

#26 [NAE-1612] Optimize Tree Case View performance with many children
  docs/_sidebar.md
  docs/views/tree_case_view.md
  projects/nae-example-app/src/app/doc/tree-view-example/tree-view-example.component.ts
  projects/netgrif-components-core/src/lib/groups/services/next-group.service.ts
  projects/netgrif-components-core/src/lib/resources/abstract-endpoint/abstract-resource.service.ts
  projects/netgrif-components-core/src/lib/user/services/user-list.service.ts
  projects/netgrif-components-core/src/lib/utility/pagination/load-all-pages.ts
  projects/netgrif-components-core/src/lib/utility/pagination/pagination-params.ts
  projects/netgrif-components-core/src/lib/utility/pagination/pagination-sort.ts
  projects/netgrif-components-core/src/lib/utility/public-api.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-endpoint.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-endpoint.ts
  projects/netgrif-components-core/src/lib/view/abstract/sortable-view.ts
  projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
  projects/netgrif-components-core/src/lib/view/public-api.ts
  projects/netgrif-components-core/src/lib/view/task-view/service/task-view.service.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/case-tree.service.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/model/tree-case-view-configuration.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/model/tree-configuration-injection-token.ts
  projects/netgrif-components-core/src/lib/view/workflow-view/workflow-view.service.ts
Labels: documentation, improvement, Medium

#38 Release 6.0.4
  .github/config.yml
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  CHANGELOG.md
  docs/_sidebar.md
  docs/views/tree_case_view.md
  package.json
  projects/nae-example-app/src/app/doc/tree-view-example/tree-view-example.component.ts
  projects/netgrif-components-core/karma.conf.js
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/schematics/collection.json
  projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
  projects/netgrif-components-core/src/lib/groups/services/next-group.service.ts
  projects/netgrif-components-core/src/lib/resources/abstract-endpoint/abstract-resource.service.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-simple-dataset.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-title.spec.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-title.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-visual-id.spec.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-visual-id.ts
  projects/netgrif-components-core/src/lib/search/models/category/category.ts
  projects/netgrif-components-core/src/lib/search/models/operator/substring.ts
  projects/netgrif-components-core/src/lib/search/search-keyword-resolver-service/search-index-resolver.service.ts
  projects/netgrif-components-core/src/lib/search/search-service/search.service.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
  projects/netgrif-components-core/src/lib/task/services/finish-task.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
  projects/netgrif-components-core/src/lib/user/services/user-list.service.ts
  projects/netgrif-components-core/src/lib/utility/pagination/load-all-pages.ts
  projects/netgrif-components-core/src/lib/utility/pagination/pagination-params.ts
  projects/netgrif-components-core/src/lib/utility/pagination/pagination-sort.ts
  projects/netgrif-components-core/src/lib/utility/public-api.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-endpoint.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-endpoint.ts
  projects/netgrif-components-core/src/lib/view/abstract/sortable-view.ts
  projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
  projects/netgrif-components-core/src/lib/view/public-api.ts
  projects/netgrif-components-core/src/lib/view/task-view/service/task-view.service.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/case-tree.service.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/model/tree-case-view-configuration.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/model/tree-configuration-injection-token.ts
  projects/netgrif-components-core/src/lib/view/workflow-view/workflow-view.service.ts
  projects/netgrif-components/karma.conf.js
  projects/netgrif-components/package.json
  projects/netgrif-components/schematics/collection.json
  projects/netgrif-components/src/lib/admin/user-invite/user-invite.component.html
  projects/netgrif-components/src/lib/admin/user-invite/user-invite.component.ts
  projects/netgrif-components/src/lib/panel/panel.component.scss
  projects/netgrif-components/src/lib/side-menu/content-components/new-case/new-case.component.html
  sonar-project.properties
Labels: Large

#39 [NAE-1470] Unable to copy from html text area
  projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.html
  projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.scss
Labels: bugfix, Extra Small

#40 [NAE-1526] - Visible HTML text area with no value displays undefined
  projects/netgrif-components-core/src/lib/data-fields/text-field/html-textarea-field/abstract-html-textarea-field.component.ts
Labels: bugfix, Extra Small

#41 [NAE-1604] - Remove case creation button if there are no nets where user can create an instance
  projects/netgrif-components-core/src/lib/utility/tests/utility/create-mock-net.ts
  projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.spec.ts
  projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.ts
  projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
Labels: improvement, Small
