Repository netgrif/components, pull requests merged in 2022-05, with the labels that each got.

#47 [NAE-1061] Resource pagination with paginator footer
  projects/nae-example-app/src/app/doc/case-view/case-view.component.html
  projects/nae-example-app/src/app/doc/case-view/case-view.component.scss
  projects/nae-example-app/src/app/doc/task-view/task-view.component.html
  projects/netgrif-components-core/src/lib/panel/public-api.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/abstract-task-list.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/default-task-panel-list/abstract-default-task-list.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/task-panel-list-pagination/abstract-task-list-pagination.component.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.spec.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/default-case-list/abstract-default-case-list.ts
  projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
  projects/netgrif-components-core/src/lib/view/public-api.ts
  projects/netgrif-components-core/src/lib/view/task-view/service/task-view.service.ts
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/panel/public-api.ts
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.html
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.scss
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.spec.ts
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.ts
  projects/netgrif-components/src/lib/view/case-view/case-view.module.ts
  projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.html
  projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.scss
  projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.spec.ts
  projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.ts
  projects/netgrif-components/src/lib/view/case-view/components/case-list/case-list.component.ts
Labels: improvement, Extra Large

#50 [NAE-1628] Reset radio buttons button visible on visible radio buttons
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-list-field/enumeration-list-field.component.html
Labels: bugfix, Extra Small

#48 [NAE-1462] Change BaseAllowedNetService to always use observables
  projects/netgrif-components-core/src/lib/allowed-nets/services/base-allowed-nets.service.ts
  projects/netgrif-components-core/src/lib/allowed-nets/services/factory/allowed-nets-service-factory.ts
Labels: improvement, Extra Small

#53 [NAE-1435] Number field value NaN causes 'Maximum call stack size exceeded'
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
Labels: bugfix, Extra Small

#49 [NAE-1363] Refactor panel featured values
  projects/netgrif-components-core/src/lib/panel/abstract/panel-with-header-binding.ts
  projects/netgrif-components-core/src/lib/panel/panel-item/abstract-panel-item.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/panel-item/abstract-panel-item.component.ts
  projects/netgrif-components-core/src/lib/panel/public-api.ts
  projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.html
  projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.html
  projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.scss
  projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.spec.ts
  projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.ts
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/panel/public-api.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
Labels: improvement, Large

#62 [NAE-1555] Required select enumeration does not display asterix
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/enumeration-autocomplete-dynamic-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.html
  projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-select-field/enumeration-select-field.component.html
Labels: Extra Small

#51 [NAE-1381] Public view task loading
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.ts
  projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
  projects/netgrif-components-core/src/lib/public/factories/public-search-factory.ts
  projects/netgrif-components-core/src/lib/view/public-api.ts
  projects/netgrif-components-core/src/lib/view/task-view/service/public-task-loading.service.spec.ts
  projects/netgrif-components-core/src/lib/view/task-view/service/public-task-loading.service.ts
Labels: bugfix, Small

#54 [NAE-1627] LDAP Groups resolving and mapping
  nae.json
  projects/nae-example-app/src/app/app.module.ts
  projects/nae-example-app/src/app/doc/ldap-group-roles-assign/ldap-group-roles-assign.component.html
  projects/nae-example-app/src/app/doc/ldap-group-roles-assign/ldap-group-roles-assign.component.scss
  projects/nae-example-app/src/app/doc/ldap-group-roles-assign/ldap-group-roles-assign.component.spec.ts
  projects/nae-example-app/src/app/doc/ldap-group-roles-assign/ldap-group-roles-assign.component.ts
  projects/nae-example-app/src/app/nae-example-app-view.service.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/0/demo-title-config-content0-task-view.component.html
  projects/nae-example-app/src/app/views/demo-title-config/content/0/demo-title-config-content0-task-view.component.scss
  projects/nae-example-app/src/app/views/demo-title-config/content/0/demo-title-config-content0-task-view.component.spec.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/0/demo-title-config-content0-task-view.component.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/1/demo-title-config-content1-case-view.component.html
  projects/nae-example-app/src/app/views/demo-title-config/content/1/demo-title-config-content1-case-view.component.scss
  projects/nae-example-app/src/app/views/demo-title-config/content/1/demo-title-config-content1-case-view.component.spec.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/1/demo-title-config-content1-case-view.component.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/2/demo-title-config-content2-case-view.component.html
  projects/nae-example-app/src/app/views/demo-title-config/content/2/demo-title-config-content2-case-view.component.scss
  projects/nae-example-app/src/app/views/demo-title-config/content/2/demo-title-config-content2-case-view.component.spec.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/2/demo-title-config-content2-case-view.component.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/3/demo-title-config-content3-case-view.component.html
  projects/nae-example-app/src/app/views/demo-title-config/content/3/demo-title-config-content3-case-view.component.scss
  projects/nae-example-app/src/app/views/demo-title-config/content/3/demo-title-config-content3-case-view.component.spec.ts
  projects/nae-example-app/src/app/views/demo-title-config/content/3/demo-title-config-content3-case-view.component.ts
  projects/nae-example-app/src/app/views/demo-title-config/title-config.component.html
  projects/nae-example-app/src/app/views/demo-title-config/title-config.component.scss
  projects/nae-example-app/src/app/views/demo-title-config/title-config.component.spec.ts
  projects/nae-example-app/src/app/views/demo-title-config/title-config.component.ts
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/admin/public-api.ts
  projects/netgrif-components-core/src/lib/admin/role-assignment-ldap-group/abstract-ldap-group-role-assignment.ts
  projects/netgrif-components-core/src/lib/admin/role-assignment-ldap-group/services/role-assignment-ldap-group.service.ts
  projects/netgrif-components-core/src/lib/groups/public-api.ts
  projects/netgrif-components-core/src/lib/groups/services/ldap-group-list.service.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/ldap-group-resource.service.ts
  projects/netgrif-components-core/src/lib/resources/interface/ldapGroupResponseBody.ts
  projects/netgrif-components-core/src/lib/resources/public-api.ts
  projects/netgrif-components/src/lib/admin/admin.module.ts
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.scss
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.spec.ts
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.theme.scss
  projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.ts
  projects/netgrif-components/src/lib/admin/public-api.ts
Labels: improvement, new feature, Extra Large

#52 [NAE-1468] i18n Data field
  angular.json
  package.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/abstract-i18n-errors.component.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/abstract-i18n-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/language-icons.service.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/language-icons.service.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field-value.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/language-icons.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-divider-field/i18n-divider-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.html
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.scss
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.ts
  projects/netgrif-components/src/lib/task-content/field-component-resolver/field-component-resolver.component.html
Labels: improvement, new feature, Extra Large
