Repository netgrif/components, pull requests merged in 2022-07, with the labels that each got.

#76 [NAE-1667] Select user translation
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html
Labels: improvement, Extra Small

#74 [NAE-1647] Elastic mapping for I18N data field
  projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
  projects/netgrif-components-core/src/lib/search/models/category/case/case-simple-dataset.ts
Labels: improvement, Small

#77 [NAE-1669] Fix header design
  projects/netgrif-components-core/src/lib/header/header-modes/search-mode/abstract-search-mode.component.ts
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/header/header-modes/search-mode/search-mode.component.html
  projects/netgrif-components/src/lib/header/header.theme.scss
  projects/netgrif-components/src/lib/tabs/tabs.module.ts
Labels: Extra Small

#78 [NAE-1658] Two-level navigation menu
  nae.json
  package.json
  projects/nae-example-app/src/app/doc/double-drawer-example/double-drawer-example.component.html
  projects/nae-example-app/src/app/doc/panels/panels.component.ts
  projects/nae-example-app/src/app/doc/sidemenu-example/sidemenu-example.component.ts
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/authorization/permission/permission.service.spec.ts
  projects/netgrif-components-core/src/lib/filter/models/case-search-request-body.ts
  projects/netgrif-components-core/src/lib/header/case-header/case-header.service.spec.ts
  projects/netgrif-components-core/src/lib/navigation/model/uri-resource.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/public-api.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri-resource.service.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.ts
  projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.spec.ts
  projects/netgrif-components-core/src/lib/process/net.spec.ts
  projects/netgrif-components-core/src/lib/process/net.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/petri-net-resource.service.spec.ts
  projects/netgrif-components-core/src/lib/resources/engine-endpoint/petri-net-resource.service.ts
  projects/netgrif-components-core/src/lib/resources/interface/case.ts
  projects/netgrif-components-core/src/lib/resources/interface/petri-net-reference.ts
  projects/netgrif-components-core/src/lib/resources/interface/task-pair.ts
  projects/netgrif-components-core/src/lib/resources/public-api.ts
  projects/netgrif-components-core/src/lib/routing/routing-builder/routing-builder.service.ts
  projects/netgrif-components-core/src/lib/utility/queue.ts
  projects/netgrif-components-core/src/lib/utility/stack.ts
  projects/netgrif-components-core/src/lib/utility/tests/utility/create-mock-net.ts
  projects/netgrif-components-core/src/lib/view/tree-case-view/tree-component/case-tree.service.spec.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.scss
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.ts
  projects/netgrif-components/src/lib/navigation/navigation.module.ts
  projects/netgrif-components/src/lib/navigation/navigation.theme.scss
  projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.spec.ts
  projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.spec.ts
Labels: critical, new feature

#79 [NAE-1658] Two-level navigation menu
  nae.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/authorization/permission/access.service.spec.ts
  projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
  projects/netgrif-components-core/src/lib/authorization/public-api.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.spec.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.ts
  projects/netgrif-components/src/lib/navigation/navigation-tree/navigation-tree.component.ts
  projects/netgrif-components/src/lib/navigation/public-api.ts
Labels: critical, new feature

#80 [NAE-1671] Dynamic case title in tab
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.ts
  projects/netgrif-components-core/src/lib/tabs/classes/opened-tab.ts
  projects/netgrif-components-core/src/lib/tabs/classes/tab-label-stream.ts
  projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
  projects/netgrif-components-core/src/lib/tabs/interfaces.ts
  projects/netgrif-components-core/src/lib/tabs/public-api.ts
  projects/netgrif-components-core/src/lib/task-content/model/task-event-notification.ts
  projects/netgrif-components-core/src/lib/task/services/assign-task.service.ts
  projects/netgrif-components-core/src/lib/task/services/cancel-task.service.ts
  projects/netgrif-components-core/src/lib/task/services/delegate-task.service.ts
  projects/netgrif-components-core/src/lib/task/services/finish-task.service.ts
  projects/netgrif-components/src/lib/tabs/tab-view/tab-view.component.html
Labels: improvement, Extra Large

#81 [NAE-1642] Redirect to transition via URL
  nae.json
  projects/nae-example-app/src/app/app.module.ts
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.html
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.scss
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.spec.ts
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
  projects/nae-example-app/src/app/nae-example-app-view.service.ts
  projects/nae-example-app/src/assets/i18n/en.json
  projects/nae-example-app/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/panel/abstract-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/public-api.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/default-task-panel-list/abstract-default-task-list.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-single/abstract-single-task.component.spec.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-single/abstract-single-task.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/models/task-panel-context.ts
  projects/netgrif-components-core/src/lib/view/public-api.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.spec.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/src/lib/panel/panel.component.html
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/panel/panel.theme.scss
  projects/netgrif-components/src/lib/panel/public-api.ts
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.html
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.scss
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.spec.ts
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.ts
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.scss
Labels: improvement, Extra Large
