Repository netgrif/components, pull requests merged in 2023-05, with the labels that each got.

#187 [NAE-1869] Incorrectly expanded task
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
Labels: bugfix, Extra Small

#189 [NAE-1874] Filtering users based on roles when selecting users for UserListField
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.spec.ts
Labels: improvement

#171 [NAE-1607] Allowed nets configuration for newly created filter
  projects/netgrif-components-core/src/lib/allowed-nets/services/factory/allowed-nets-service-factory.ts
  projects/netgrif-components-core/src/lib/filter/models/user-filter-constants.ts
Labels: improvement, Extra Small

#193 Release 6.2.9
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/search/models/operator/substring.ts
  projects/netgrif-components-core/src/lib/search/search-service/search.service.ts
  projects/netgrif-components/package.json
Labels: Extra Small

#194 [NAE-1881] Release 6.3.0-rc.9
  CHANGELOG.md
  projects/nae-example-app/src/app/app.module.ts
  projects/netgrif-components/src/lib/filter-field-content/filter-field-content.module.ts
  projects/netgrif-components/src/lib/filter-field-content/filter-field-tab-view/filter-field-tab-view.component.ts
  projects/netgrif-components/src/lib/filter-field-content/filter-field-tabbed-task-view/filter-field-tabbed-task-view.component.html
  projects/netgrif-components/src/lib/filter-field-content/filter-field-tabbed-task-view/filter-field-tabbed-task-view.component.scss
  projects/netgrif-components/src/lib/filter-field-content/filter-field-tabbed-task-view/filter-field-tabbed-task-view.component.spec.ts
  projects/netgrif-components/src/lib/filter-field-content/filter-field-tabbed-task-view/filter-field-tabbed-task-view.component.ts
  projects/netgrif-components/src/lib/filter-field-content/public-api.ts
Labels: improvement, Medium

#196 [NAE-1889] Process list is not refreshed after uploading process file
  projects/netgrif-components-core/src/lib/view/workflow-view/abstract-workflow-view.component.ts
Labels: bugfix, Extra Small

#195 [NAE-1885] Side panel creates a new case when pressing Enter on date field
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
  projects/netgrif-components-core/src/lib/side-menu/models/side-menu-control.ts
Labels: bugfix, Extra Small

#125 [NAE-1687] Factory class as providers
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
  projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.ts
  projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
  projects/netgrif-components-core/src/lib/providers/base-filter/base-filter-factory.provider.ts
  projects/netgrif-components-core/src/lib/providers/case-resource/case-resource-service.provider.ts
  projects/netgrif-components-core/src/lib/providers/petrinet-resource/petrinet-resource-service.provider.ts
  projects/netgrif-components-core/src/lib/providers/process-service/process-service.provider.ts
  projects/netgrif-components-core/src/lib/providers/public-api.ts
  projects/netgrif-components-core/src/lib/providers/task-resource/task-resource-service.provider.ts
  projects/netgrif-components-core/src/public-api.ts
Labels: improvement, Large
