Repository netgrif/components, pull requests merged in 2023-11, with the labels that each got.

#218 [NAE-1921] User field value cannot be cleared
  projects/netgrif-components-core/src/lib/data-fields/user-field/abstract-user-field.component.ts
  projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html
Labels: bug, improvement, bugfix, critical, Extra Small

#213 [NAE-1914] revertToPreviousValue - change is always false
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: bugfix, Extra Small

#221 [NAE-1925] Panel is not opening
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.html
Labels: bug, bugfix, Extra Large

#220 [NAE-1924] Neziadane volanie setData z FE
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
Labels: bug, bugfix, Extra Large

#219 [NAE-1923] DateTime doesn't have locale and rework validation to isoWeekday
  projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/abstract-time-instance-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/models/abstract-time-instance-field.ts
  projects/netgrif-components/src/lib/data-fields/date-field/date-field.component.ts
  projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.ts
Labels: bug, bugfix, Small

#223 v6.3.2
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/abstract-time-instance-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/models/abstract-time-instance-field.ts
  projects/netgrif-components-core/src/lib/data-fields/user-field/abstract-user-field.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/date-field/date-field.component.ts
  projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.ts
  projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html
Labels: Medium
