Repository netgrif/components, pull requests merged in 2023-03, with the labels that each got.

#181 [NAE-1839] Public view - fields after auto assign are still only visible
  projects/netgrif-components-core/src/lib/task/services/assign-policy.service.ts
  projects/netgrif-components-core/src/lib/user/services/user.service.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts
Labels: bugfix, Extra Small

#178 [NAE-1832] Security upgrade moment from 2.24.0 to 2.29.4
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components/package.json
Labels: Extra Small

#182 [NAE-1841] Idle timer component
  nae.json
  projects/nae-example-app/src/app/app.component.html
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/authentication/components/abstract-session-idle.component.spec.ts
  projects/netgrif-components-core/src/lib/authentication/components/abstract-session-idle.component.ts
  projects/netgrif-components-core/src/lib/authentication/public-api.ts
  projects/netgrif-components-core/src/lib/authentication/services/authentication-interceptor.ts
  projects/netgrif-components-core/src/lib/authentication/session/public-api.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session-idle-timer.service.spec.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session-idle-timer.service.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session.service.ts
  projects/netgrif-components-core/src/lib/configuration/configuration.service.spec.ts
  projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
  projects/netgrif-components-core/src/lib/forms/models/abstract-registration.component.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.spec.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/test-config.ts
  projects/netgrif-components-core/src/schema/example.nae.json
  projects/netgrif-components-core/src/schema/nae-schema.json
  projects/netgrif-components/src/lib/authentication/auth.module.ts
  projects/netgrif-components/src/lib/authentication/public-api.ts
  projects/netgrif-components/src/lib/authentication/session-idle/popup-session-idle/popup-session-idle.component.html
  projects/netgrif-components/src/lib/authentication/session-idle/popup-session-idle/popup-session-idle.component.scss
  projects/netgrif-components/src/lib/authentication/session-idle/popup-session-idle/popup-session-idle.component.ts
  projects/netgrif-components/src/lib/authentication/session-idle/session-idle.component.html
  projects/netgrif-components/src/lib/authentication/session-idle/session-idle.component.ts
Labels: Large

#116 [NAE-1431] Login view redirect configuration
  nae.json
  projects/netgrif-components-core/src/commons/schema.ts
  projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/logout-shortcut/abstract-logout-shortcut.component.ts
  projects/netgrif-components-core/src/lib/routing/redirect-service/redirect.service.ts
  projects/netgrif-components-core/src/schema/nae-schema.json
  projects/netgrif-components/schematics/view/create-view-prompt/views/login/files/__className@dasherize__.component.ts.template
  projects/netgrif-components/src/lib/forms/login/login-form.component.html
  projects/netgrif-components/src/lib/forms/login/login-form.component.scss
Labels: Small

#183 [NAE-1851] Save selected headers in filter
  projects/nae-example-app/src/app/doc/demo-title-config/content/1/demo-title-config-content1-case-view.component.ts
  projects/nae-example-app/src/app/doc/demo-title-config/content/2/demo-title-config-content2-case-view.component.ts
  projects/nae-example-app/src/app/doc/demo-title-config/content/3/demo-title-config-content3-case-view.component.ts
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.ts
  projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
  projects/netgrif-components-core/src/lib/tabs/interfaces.ts
Labels: bugfix, new feature, Extra Small

#185 Release/6.2.8
  CHANGELOG.md
  package.json
  projects/nae-example-app/src/app/doc/demo-title-config/content/1/demo-title-config-content1-case-view.component.ts
  projects/nae-example-app/src/app/doc/demo-title-config/content/2/demo-title-config-content2-case-view.component.ts
  projects/nae-example-app/src/app/doc/demo-title-config/content/3/demo-title-config-content3-case-view.component.ts
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.ts
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
  projects/netgrif-components-core/src/lib/tabs/interfaces.ts
  projects/netgrif-components/package.json
Labels: Extra Small, release

#166 [NAE-1809] UserList field show selected users
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/public-api.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/abstract-multi-user-assign.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/abstract-multi-user-assign.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/base-user-assign-list/abstract-base-user-assign-list.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/base-user-assign-list/abstract-base-user-assign-list.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/multi-user-assign-list/abstract-multi-user-assign-list.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/multi-user-assign-list/abstract-multi-user-assign-list.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/multi-user-assign-list/multi-user-assign-item/abstract-multi-user-assign-item.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/multi-user-assign-list/multi-user-assign-item/abstract-multi-user-assign-item.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/user-assign-list/abstract-user-assign-list.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components-core/src/lib/utility/contains.pipe.spec.ts
  projects/netgrif-components-core/src/lib/utility/contains.pipe.ts
  projects/netgrif-components-core/src/lib/utility/public-api.ts
  projects/netgrif-components-core/src/lib/utility/utility.module.ts
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-item/multi-user-assign-item.component.html
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-item/multi-user-assign-item.component.scss
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-item/multi-user-assign-item.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-item/multi-user-assign-item.component.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.html
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.scss
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign.component.html
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign.component.scss
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign.component.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/side-menu-multi-user-assign-component.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/public-api.ts
  projects/netgrif-components/src/lib/side-menu/content-components/side-menu-content-component.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/user-assign/side-menu-user-assign-component.module.ts
Labels: improvement, Extra Large

#168 [NAE-1802] TaskRef-ed fields behavior update unaware of parent task behaviour
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
Labels: bugfix, Extra Small
