Repository netgrif/components, pull requests merged in 2023-12, with the labels that each got.

#224 [NAE-1926] Can't close Tab in Tab view
  projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
Labels: bug, bugfix, Extra Large

#227 [NAE-1929] Data field type list of strings
  projects/netgrif-components-core/src/lib/data-fields/models/component.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/data-fields/string-collection-field/models/string-collection-field.ts
  projects/netgrif-components-core/src/lib/data-fields/string-collection-field/string-collection-default-field/abstract-string-collection-default-field.component.ts
  projects/netgrif-components-core/src/lib/task-content/model/field-type-resource.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.html
  projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.scss
  projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.ts
Labels: improvement, new feature, Medium

#226 [NAE-1933] UserList deleteAll button
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts
Labels: improvement, Extra Small
