Repository netgrif/components, pull requests merged in 2023-02, with the labels that each got.

#164 [NAE-1804] In UserList field can choose one user multiple times
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.spec.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts
Labels: bugfix, Small

#175 [NAE-1825] Fix the upstream dependency conflict
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  package.json
  projects/nae-example-app/src/app/doc/drawer-example/drawer-example.component.html
  projects/netgrif-components-core/schematics/_utility/utility-functions.ts
  projects/netgrif-components-core/src/lib/authentication/services/methods/basic-authentication/basic-authentication.service.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components/schematics/view/create-view-prompt/views/sidenav-toolbar-view/create-sidenav-or-toolbar-view.ts
Labels: Small

#174 [NAE-1822] Task list broken scrolling
  package.json
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/panel/task-panel-list/task-list.component.html
Labels: bugfix, Extra Small

#177 [NAE-1830] Changing columns in owerflowService deletes all set columns
  projects/netgrif-components-core/src/lib/header/abstract-header-service.ts
  projects/netgrif-components-core/src/lib/header/abstract-header.component.ts
  projects/netgrif-components-core/src/lib/header/header-modes/edit-mode/abstract-edit-mode.component.ts
  projects/netgrif-components-core/src/lib/header/header-state.ts
Labels: bugfix, Extra Small

#176 [NAE-1827] Dynamic enumeration looses focus after querying for data
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/abstract-enumeration-autocomplete-dynamic-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
  projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: bugfix, Small

#173 [NAE-1823] Error when searching for non-existing tasks
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.html
  projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
  projects/nae-example-app/src/assets/i18n/en.json
  projects/nae-example-app/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/panel/task-panel-single/abstract-single-task.component.ts
  projects/netgrif-components-core/src/lib/utility/directives/let.directive.spec.ts
  projects/netgrif-components-core/src/lib/utility/directives/let.directive.ts
  projects/netgrif-components-core/src/lib/utility/public-api.ts
  projects/netgrif-components-core/src/lib/utility/utility.module.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.spec.ts
  projects/netgrif-components-core/src/lib/view/task-view/abstract-single-task-view.component.ts
  projects/netgrif-components/src/lib/panel/panel.module.ts
  projects/netgrif-components/src/lib/panel/task-panel-single/single-task.component.html
Labels: bugfix, Medium
