Repository netgrif/components, pull requests merged in 2024-01, with the labels that each got.

#234 Release/6.3.3
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/authentication/services/authentication/authentication.service.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session-idle-timer.service.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/language-selector/abstract-language-selector.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/side-menu-container/abstract-side-menu-container.component.spec.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-authentication.service.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.spec.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts
  projects/netgrif-components/src/lib/panel/task-panel-list/task-list.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.spec.ts
  projects/netgrif-components/src/lib/tabs/tab-view/tab-view.component.spec.ts
Labels: Small, release

#233 [NAE-1939] Problem with Tests
  CHANGELOG.md
  package.json
  projects/netgrif-components-core/package.json
  projects/netgrif-components-core/src/lib/authentication/services/authentication/authentication.service.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/language-selector/abstract-language-selector.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/side-menu-container/abstract-side-menu-container.component.spec.ts
  projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-authentication.service.ts
  projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.spec.ts
  projects/netgrif-components/package.json
  projects/netgrif-components/src/lib/panel/task-panel-list/task-list.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/user-assign/user-assign-list/user-assign-list.component.spec.ts
  projects/netgrif-components/src/lib/tabs/tab-view/tab-view.component.spec.ts
Labels: bug, bugfix, critical, Small

#228 [NAE-1936] Disable create case button using menu items
  docs/_sidebar.md
  docs/views/default-tabbed-case-view.md
  projects/netgrif-components-core/src/lib/navigation/model/group-navigation-constants.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/model/new-case-injection-data.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.html
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
Labels: new feature, Extra Small

#230 [NAE-1935] Improved breadcrumbs from menu items
  docs/views/breadcrumbs/breadcrumbs.md
  docs/views/breadcrumbs/img.png
  docs/views/breadcrumbs/img_1.png
  projects/netgrif-components-core/src/lib/navigation/breadcrumbs/abstract-breadcrumbs.component.ts
  projects/netgrif-components-core/src/lib/navigation/service/uri.service.ts
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.html
  projects/netgrif-components/src/lib/navigation/breadcrumbs/breadcrumbs.component.ts
Labels: improvement, Medium, upgrade
