Repository netgrif/components, pull requests merged in 2024-02, with the labels that each got.

#191 [NAE-1876] Process URI v2
  projects/netgrif-components-core/src/lib/side-menu/content-components/import-net/abstract-import-net.component.spec.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/import-net/abstract-import-net.component.ts
  projects/netgrif-components-core/src/lib/side-menu/side-menu-container/abstract-side-menu-container.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/import-net/import-net.component.spec.ts
  projects/netgrif-components/src/lib/side-menu/content-components/import-net/import-net.component.ts
Labels: improvement, Extra Small

#236 [NAE-1948] Bugs after merge to 6.4.0
  projects/nae-example-app/src/app/app.module.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field.ts
  projects/netgrif-components-core/src/lib/data-fields/user-list-field/user-list-default-field/abstract-user-list-default-field.component.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/abstract-multi-user-assign.component.ts
  projects/netgrif-components/nae-theme.scss
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
  projects/netgrif-components/src/lib/data-fields/user-field/user-default-field/user-default-field.component.html
  projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-default-field/user-list-default-field.component.html
  projects/netgrif-components/src/lib/dialog/multi-user-assign-dialog/multi-user-assign-dialog.component.ts
Labels: Extra Small

#232 [NAE-1920] Injection token NAE_USER_ASSIGN_COMPONENT breaks delegate
  projects/netgrif-components-core/src/lib/dialog/injection-tokens.ts
  projects/netgrif-components-core/src/lib/side-menu/content-components/injection-tokens.ts
  projects/netgrif-components/src/lib/dialog/dialog.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/import-net/side-menu-import-net-component.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/side-menu-multi-user-assign-component.module.ts
  projects/netgrif-components/src/lib/side-menu/content-components/side-menu-content-component.module.ts
Labels: bug, bugfix, Extra Small

#231 [NAE-1879] Language register
  nae.json
  projects/nae-example-app/src/app/app.component.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/language-icons.service.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/abstract-quick-panel.component.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/language-selector/abstract-language-selector.component.spec.ts
  projects/netgrif-components-core/src/lib/navigation/quick-panel/components/language-selector/abstract-language-selector.component.ts
  projects/netgrif-components-core/src/lib/translate/default-language-injection-token.ts
  projects/netgrif-components-core/src/lib/translate/language.service.spec.ts
  projects/netgrif-components-core/src/lib/translate/language.service.ts
  projects/netgrif-components-core/src/lib/translate/public-api.ts
  projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
  projects/netgrif-components/src/lib/navigation/quick-panel/components/language-selector/language-selector.component.html
  projects/netgrif-components/src/lib/navigation/quick-panel/components/language-selector/language-selector.component.scss
  projects/netgrif-components/src/lib/navigation/quick-panel/components/language-selector/language-selector.component.ts
  projects/netgrif-components/src/lib/navigation/quick-panel/components/quick-panel.component.html
Labels: improvement, new feature, Medium
