Repository netgrif/components, pull requests merged in 2024-03, with the labels that each got.

#206 [NAE-1905] Add bold on i18n text plainText field
  projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.ts
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.html
  projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.scss
Labels: improvement, new feature, Extra Small

#229 [NAE-1922] Signature Pad Field
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
  projects/netgrif-components/src/lib/data-fields/text-field/signature-pad-field/signature-pad-field.component.html
  projects/netgrif-components/src/lib/data-fields/text-field/signature-pad-field/signature-pad-field.component.scss
  projects/netgrif-components/src/lib/data-fields/text-field/signature-pad-field/signature-pad-field.component.spec.ts
  projects/netgrif-components/src/lib/data-fields/text-field/signature-pad-field/signature-pad-field.component.ts
Labels: improvement, new feature, Medium

#238 [NAE-1949] Allowed Types for Filefield
  projects/netgrif-components-core/src/assets/i18n/de.json
  projects/netgrif-components-core/src/assets/i18n/en.json
  projects/netgrif-components-core/src/assets/i18n/sk.json
  projects/netgrif-components-core/src/lib/data-fields/file-field/file-default-field/abstract-file-default-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/file-field/models/file-field.ts
  projects/netgrif-components-core/src/lib/data-fields/file-list-field/file-list-default-field/abstract-file-list-default-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/models/abstract-file-field-default-component.ts
  projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
  projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Labels: improvement, Medium

#237 [NAE-1948] Bugs after merge to 6.4.0
  projects/netgrif-components-core/src/lib/data-fields/data-field-template/abstract-data-field-template.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
  projects/netgrif-components/src/lib/data-fields/button-field/button-default-field/button-default-field.component.html
  projects/netgrif-components/src/lib/data-fields/button-field/button-default-field/button-default-field.component.scss
  projects/netgrif-components/src/lib/data-fields/data-field-template/data-field-template.component.html
  projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
Labels: Extra Small

#240 [NAE-1957] Allow filter to caseRef field and variants
  projects/netgrif-components-core/src/lib/data-fields/case-ref-field/case-ref-default/case-ref-default.component.ts
  projects/netgrif-components-core/src/lib/data-fields/case-ref-field/model/abstract-case-ref-base-field-component.ts
  projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-caseref-field/abstract-enumeration-caseref-field.component.ts
  projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-caseref-field/abstract-multichoice-caseref-field.component.ts
Labels: Medium
