Repository netgrif/components, pull requests merged in 2025-09, with the labels that each got.

#297 [NAE-2188] Wrong remote configuration loading order
  docs/compodoc/components-core/coverage.html
  docs/compodoc/components-core/miscellaneous/functions.html
  docs/compodoc/components-core/unit-test.html
  docs/typedoc/components-core/functions/authenticationServiceFactory.html
  projects/nae-example-app/src/app/nae-example-app-configuration.service.ts
  projects/nae-example-app/src/environments/environment.prod.ts
  projects/nae-example-app/src/environments/environment.ts
  projects/nae-example-app/src/main.ts
  projects/netgrif-components-core/src/lib/authentication/authentication.factory.spec.ts
  projects/netgrif-components-core/src/lib/authentication/authentication.factory.ts
  projects/netgrif-components-core/src/lib/authentication/authentication.module.ts
  projects/netgrif-components-core/src/lib/authentication/proxyAuthentication.service.spec.ts
  projects/netgrif-components-core/src/lib/authentication/proxyAuthentication.service.ts
  projects/netgrif-components-core/src/lib/authentication/public-api.ts
  projects/netgrif-components-core/src/lib/authentication/services/authentication/authentication.service.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session-idle-timer.service.ts
  projects/netgrif-components-core/src/lib/authentication/session/services/session.service.ts
  projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
  projects/netgrif-components-core/src/lib/data-fields/date-field/date-default-field/abstract-date-default-field.component.spec.ts
  projects/netgrif-components-core/src/lib/header/case-header/case-menta-enum.ts
  projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.spec.ts
  projects/netgrif-components-core/src/lib/resources/abstract-endpoint/abstract-resource.service.ts
  projects/netgrif-components-core/src/lib/translate/language.service.ts
  projects/netgrif-components-core/src/lib/user/services/user.service.ts
Labels: bugfix, Large

#296 [NAE-2197] Wrong elastic sort
  projects/netgrif-components-core/src/lib/header/task-header/task-meta-enum.ts
Labels: bugfix, Extra Small

#299 [NAE-2205] DefaultCaseRefListViewComponent - headers not displayed when processes exceed single view
  projects/netgrif-components-core/src/lib/allowed-nets/services/factory/allowed-nets-service-factory.ts
  projects/netgrif-components-core/src/lib/data-fields/case-ref-field/model/abstract-case-ref-base-field-component.ts
  projects/netgrif-components-core/src/lib/data-fields/case-ref-field/model/case-ref-injection-tokens.ts
  projects/netgrif-components-core/src/lib/data-fields/public-api.ts
  projects/netgrif-components-core/src/lib/data-fields/task-ref-field/model/task-ref-injection-tokens.ts
  projects/netgrif-components-core/src/lib/data-fields/task-ref-field/task-ref-list-field/abstract-task-ref-list-field.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel-list/default-task-panel-list/abstract-default-task-list.component.ts
  projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-case-ref-list-view/default-case-ref-list-view.component.html
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-case-ref-list-view/default-case-ref-list-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-case-ref-list-view/default-case-ref-list-view.component.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-task-view/default-task-view.component.html
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-task-view/default-task-view.component.spec.ts
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/refs/default-task-view/default-task-view.component.ts
  projects/netgrif-components/src/lib/panel/panel.component.html
  projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.html
  projects/netgrif-components/src/lib/panel/task-panel-list/task-list.component.html
  projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html
Labels: bugfix, Large

#300 [NAE-2218] Misaligned header on case view when displayed below 1920px
  projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.html
  projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/tabbed/default-tabbed-case-view/default-tabbed-case-view.component.html
Labels: bugfix
